### ISSUE TITLE
Confusion With multiple go routines 

### ISSUE THREAD

**Issue by adhamelia** [Iceber/iouring-go#15]
@Iceber 

just wanted to know can I use and share a single instance with multiple go routines??? If I am doing it my app randomly gets stuck and it seems to have a deadlock scenario…

**Comment by Iceber** [comment]
Based on my research experience a year ago, we may need to have a goroutinue exclusive to iouring, and then other events sent to it via channel.

**Comment by adhamelia** [comment]
Thanks @Iceber. got your point.
