### ISSUE TITLE
panic: iouring_setup: function not implemented

### ISSUE THREAD

**Issue by yuchen-sun** [Iceber/iouring-go#19]
When I tested the cat in /example, it was panic on my machine(CentOS Stream9).
But, when I tested the cat in Ubuntu22.04, It can work normally.
# env
```bash
uname -a
Linux 5.14.0-160.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 25 23:06:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```bash
uname -a
Linux 5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Iceber** [comment]
Could you give me the output of panic?

**Comment by yuchen-sun** [comment]
> Could you give me the output of panic?
Like the title

![image](https://user-images.githubusercontent.com/37729051/189021278-cf4692f7-c7c2-4c11-85a9-f95eadd662a6.png)

**Comment by Iceber** [comment]
Please run the command on centos and Ubuntu separately to see their output
```bash
printf SYS_io_uring_setup | gcc -include sys/syscall.h -E -
```

**Comment by yuchen-sun** [comment]
> ```shell
> printf SYS_io_uring_setup | gcc -include sys/syscall.h -E -
> ```
centos stream9
```bash
[root@test-bs cat]# printf SYS_io_uring_setup | gcc -include sys/syscall.h -E -
# 0 "<stdin>"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "/usr/include/sys/syscall.h" 1 3 4
# 24 "/usr/include/sys/syscall.h" 3 4
# 1 "/usr/include/asm/unistd.h" 1 3 4
# 20 "/usr/include/asm/unistd.h" 3 4
# 1 "/usr/include/asm/unistd_64.h" 1 3 4
# 21 "/usr/include/asm/unistd.h" 2 3 4
# 25 "/usr/include/sys/syscall.h" 2 3 4




# 1 "/usr/include/bits/syscall.h" 1 3 4
# 30 "/usr/include/sys/syscall.h" 2 3 4
# 0 "<command-line>" 2
# 1 "<stdin>"

# 1 "<stdin>" 3 4
425
```

**Comment by yuchen-sun** [comment]
> 请分别在 centos 和 Ubuntu 上运行命令以查看它们的输出
> 
> ```shell
> $ printf SYS_io_uring_setup | gcc -include sys/syscall.h -E -
> ```

Ubuntu22.04
```bash
# 0 "<stdin>"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "/usr/include/x86_64-linux-gnu/sys/syscall.h" 1 3 4
# 24 "/usr/include/x86_64-linux-gnu/sys/syscall.h" 3 4
# 1 "/usr/include/x86_64-linux-gnu/asm/unistd.h" 1 3 4
# 20 "/usr/include/x86_64-linux-gnu/asm/unistd.h" 3 4
# 1 "/usr/include/x86_64-linux-gnu/asm/unistd_64.h" 1 3 4
# 21 "/usr/include/x86_64-linux-gnu/asm/unistd.h" 2 3 4
# 25 "/usr/include/x86_64-linux-gnu/sys/syscall.h" 2 3 4




# 1 "/usr/include/x86_64-linux-gnu/bits/syscall.h" 1 3 4
# 30 "/usr/include/x86_64-linux-gnu/sys/syscall.h" 2 3 4
# 0 "<command-line>" 2
# 1 "<stdin>"

# 1 "<stdin>" 3 4
425
```

**Comment by Iceber** [comment]
Weird problem, but apparently the kernel doesn't support iouring, maybe the centos kernel compile option doesn't enable iouring, you can try this https://unix.stackexchange.com/questions/596276/how-to-tell-if-a-linux-machine-supports-io-uring

**Comment by yuchen-sun** [comment]
> Weird problem, maybe the centos kernel compile option doesn't enable iouring, you can try this https://unix.stackexchange.com/questions/596276/how-to-tell-if-a-linux-machine-supports-io-uring

you are right! thanks.
![image](https://user-images.githubusercontent.com/37729051/189029248-cb688536-4a59-41ed-951c-ef72f766ba6c.png)
