### ISSUE TITLE
是否支持 ReadAt 操作？

### ISSUE THREAD

**Issue by ringsaturn** [Iceber/iouring-go#29]
我想以非常高的频率随机读取文件的特定部分，看了文档没有找到相关的函数，只有 Read/Readv 这两个，想问下是否支持 ReadAt 的方式：

```go
func (f *File) ReadAt(b []byte, off int64) (n int, err error)
```

**Comment by Iceber** [comment]
看起来可以用这个
https://github.com/Iceber/iouring-go/blob/002cfd2e2a9021c13192f3bd4d9023374e38c93f/prep_request.go#L105

**Comment by ringsaturn** [comment]
多谢，试了下是预期的结果
